In [1]:

def DivideByZero(x,y):
    try:
        x/y
    except ZeroDivisionError as e:
        print("An interger/number can't be divisible by Zero")
        print("An execption has been occured as, ",e, " action has been attempted")

# apply values on variable x & y
x,y=5,0

#Function Execute
DivideByZero(x,y)

An interger/number can't be divisible by Zero
An execption has been occured as,  division by zero  action has been attempted


In [2]:

subject=["Americans","Indians"]
verb=["play","watch"]
objects=["Baseball","Cricket"]
# List Comprehension  #for Loop for Iteration
Syntax = [(Sub+' '+vrb+' '+Objct+".") for Sub in subject for vrb in verb for Objct in objects]
print("Output:")
for syn in Syntax:    
    print(syn)

Output:
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


In [3]:

import numpy as num_py
def matrix_Vandermonde(input_vector,n,bool_arg):
    output_matrix=num_py.vander(x=input_vector,N=n,increasing=bool_arg)
    return output_matrix
input_vector = num_py.arange(5,13,2)   
n = 5       
bool_arg_T = True                     
bool_arg_F = False                    

out_matrix_True=matrix_Vandermonde(input_vector,n,bool_arg_T)

out_matrix_False=matrix_Vandermonde(input_vector,n,bool_arg_F)

print("Input vector \n",input_vector,"\n")
print("Output Matrix , when boolean argument is True: \n",out_matrix_True,"\n")
print("Output Matrix , when boolean argument is False: \n",out_matrix_False)

Input vector 
 [ 5  7  9 11] 

Output Matrix , when boolean argument is True: 
 [[    1     5    25   125   625]
 [    1     7    49   343  2401]
 [    1     9    81   729  6561]
 [    1    11   121  1331 14641]] 

Output Matrix , when boolean argument is False: 
 [[  625   125    25     5     1]
 [ 2401   343    49     7     1]
 [ 6561   729    81     9     1]
 [14641  1331   121    11     1]]
